name=PZEM004Tv40_R4
version=1.1.1
author=Bharani Dharan Rangaraj <bharanidharanrangaraj@gmail.com>
maintainer=Bharani Dharan Rangaraj <bharanidharanrangaraj@gmail.com>
sentence=Library for PZEM-004T V4.0 Energy Monitor. Compatible with Arduino UNO R3, R4, Nano, and Mega.
paragraph=Supports reading voltage, current, power, energy, frequency, power factor, and alarm status from PZEM-004T-100A using Modbus RTU protocol. Compatible with Arduino UNO R3, R4 Minima, R4 WiFi, Nano, and Mega. Built-in error handling and CRC verification.
category=Sensors
url=https://github.com/bharanidharanrangaraj/PZEM004Tv40_R4
architectures=renesas_uno, arduino_avr
includes=PZEM004Tv40_R4.h